spring:

  datasource:
    hikari.jdbc-url: jdbc:h2:mem:test_db;
    username: sa
    password:

  jpa:
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
